spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: water
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    port: 5672
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 2
    maxActive: 20
    minIdle: 0
    maxWait: 6000
  freemarker:
    check-template-location: true
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
    cache: false
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hg.seckill.model
  configuration:
    map-underscore-to-camel-case: true
upload:
  path: D:/TestFile/
redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  timeout: 15000
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500